JS_2SEM/aula_05 - Kanban/Grafico/Models/ErrorViewModel.cs
namespace Grafico.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

JS_2SEM/aula_05 - Kanban/Grafico/Controllers/AtividadeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Grafico.Controllers
{
    public class AtividadeController : Controller
    {
        private readonly ILogger<AtividadeController> _logger;

        public AtividadeController(ILogger<AtividadeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

JS_2SEM/aula_05 - Kanban/Grafico/Controllers/ContinenteController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Grafico.Controllers
{
    [Route("[controller]")]
    public class ContinenteController : Controller
    {
        private readonly ILogger<ContinenteController> _logger;

        public ContinenteController(ILogger<ContinenteController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

JS_2SEM/aula_05 - Kanban/Grafico/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Grafico.Models;

namespace Grafico.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

JS_2SEM/aula_05 - Kanban/Grafico/Controllers/PaisController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Grafico.Controllers
{
    [Route("[controller]")]
    public class PaisController : Controller
    {
        private readonly ILogger<PaisController> _logger;

        public PaisController(ILogger<PaisController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

JS_2SEM/aula_05 - Kanban/Grafico/Views/Atividade/Index.cshtml
@section scripts{
    <script src="~/js/kamban.js"></script>
}

@{
    ViewData["Title"] = "Index";
}

<style>
    .dragging{
        opacity: 0.5;
    }
</style>
    <div class="row mt-5 justify-content-center">
       
    <div class="col-4">
        <h3 class="text-center bg-danger text-light">À fazer</h3>
        <div style="height: 500px;" class="column col-12 bg-danger bg-opacity-25 p-4">
            <div class="item col-6 bg-info m-3 p-4 rounded-start-3" draggable="true">Card 01</div>
            <div class="item col-6 bg-info m-3 p-4 rounded-start-3" draggable="true">Card 02</div>
        </div>
    </div>
   
    <div class="col-4">
        <h3 class="text-center bg-warning text-light">Fazendo</h3>
        <div style="height: 500px;" class="column col-12 bg-warning bg-opacity-25 p-4">
            <div class="item col-6 bg-info m-3 p-4 rounded-start-3" draggable="true">Card 03</div>
            <div class="item col-6 bg-info m-3 p-4 rounded-start-3" draggable="true">Card 04</div>
        </div>
    </div>
   
    <div class="col-4">
        <h3 class="text-center bg-success text-light">Feito</h3>
        <div style="height: 500px;" class="column col-12 bg-success  bg-opacity-25 p-4">
            <div class="item col-6 bg-info m-3 p-4 rounded-start-3" draggable="true">Card 05</div>
            <div class="item col-6 bg-info m-3 p-4 rounded-start-3" draggable="true">Card 06</div>
        </div>
    </div>
</div>

JS_2SEM/aula_05 - Kanban/Grafico/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

JS_2SEM/aula_05 - Kanban/Grafico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Grafico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Grafico.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Grafico</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Atividade" asp-action="Index">kanban</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Grafico - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>